name: gofast-0.1.0
channels:
  - conda-forge
  - defaults
dependencies:
    - setuptools
    - scikit-learn >=1.1.2
    - cython >=0.29.33
    - h5py >=3.2.0
    - joblib >=1.2.0
    - matplotlib ==3.5.2
    - sqlalchemy
    - missingno >=0.4.2
    - numpy <=1.23.0
    - openpyxl >=3.0.3
    - pandas >=1.4.0
    - pyproj >=3.3.0
    - python >=3.9
    - pyyaml >=5.0.0
    - scipy >=1.9.0
    - seaborn >=0.12.0
    - pytables >=3.6.1
    - threadpoolctl >=3.1.0
    - tqdm >=4.64.1
    - xgboost >=1.5.0
    - yellowbrick >=1.5.0
    - click >=8.0.4 
    - statsmodels
    - docutils                            