name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Configure Conda
      run: |
        echo "Configuring conda..."
        conda config --set channel_priority strict
        conda config --set solver classic 
    - name: Update Conda and Install dependencies
      run: |
        echo "Updating conda environment..."
        conda env update --file environment.yml --name base
    - name: Install gofast package
      run: |
        # conda run --name base pip install -e .
        python -m pip install .    
    - name: Lint with flake8
      run: |
        conda install flake8 -y
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
        
    - name: Debugging Information
      if: failure() # This step runs only if the previous steps fail
      run: |
        echo "Printing debug information..."
        echo "PATH=$PATH"
        conda info
        conda list

# name: Python Package using Conda

# on: [push]

# jobs:
#   build-linux:
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 5

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.10'

#     - name: Setup Miniconda
#       uses: conda-incubator/setup-miniconda@v2
#       with:
#         auto-update-conda: true
#         python-version: '3.10'
#         activate-environment: base

#     - name: Configure Conda and Install Dependencies
#       run: |
#         echo "Configuring conda..."
#         conda config --set channel_priority strict
#         conda config --set solver classic
#         echo "Updating conda environment..."
#         conda env update --file environment.yml --name base
#         conda list

#     - name: Install gofast package
#       run: |
#         python -m pip install .

#     - name: Install flake8 using pip
#       run: |
#         pip install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#     - name: Install and Test with pytest
#       run: |
#         conda install pytest -y
#         pytest

#     - name: Debugging Information
#       if: failure() # This step runs only if the previous steps fail
#       run: |
#         echo "Printing debug information..."
#         echo "PATH=$PATH"
#         conda info
#         conda list

