name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: base
        environment-file: environment.yml
        python-version: '3.10'
        auto-activate-base: true

    - name: Install gofast package
      run: |
        python -m pip install .

    - name: Lint with flake8
      run: |
        conda install flake8 -y
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

    - name: Debugging Information
      if: failure() # This step runs only if the previous steps fail
      run: |
        echo "Printing debug information..."
        echo "PATH=$PATH"
        conda info
        conda list
